title: "Cloud & DevSecOps Portfolio"
description: "Showcasing projects, blog posts, and cloud solutions."

# Enable SCSS processing
sass:
  sass_dir: _sass  # This explicitly sets the SCSS directory
  style: compressed  # Use 'expanded' for easier debugging

